/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckPrintRouteImport } from './routes/deck.print'

const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckPrintRoute = DeckPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => DeckRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/deck/print': typeof DeckPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/deck/print': typeof DeckPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck': typeof DeckRouteWithChildren
  '/deck/print': typeof DeckPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck' | '/deck/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck' | '/deck/print'
  id: '__root__' | '/' | '/deck' | '/deck/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckRoute: typeof DeckRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/print': {
      id: '/deck/print'
      path: '/print'
      fullPath: '/deck/print'
      preLoaderRoute: typeof DeckPrintRouteImport
      parentRoute: typeof DeckRoute
    }
  }
}

interface DeckRouteChildren {
  DeckPrintRoute: typeof DeckPrintRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckPrintRoute: DeckPrintRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckRoute: DeckRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
